#include "hal_data.h"
#include "debug_uartRV/uartrv.h"
#include "stdio.h"
#include "debug_uart/uart.h"
#include "debug_dac/bsp_dac.h"
#include "debug_pwm/pwm.h"


#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

        fsp_err_t err;
        uint8_t rx_packet[UART2_LINE_BUF_SIZE];
        uint16_t rx_len;
        Gpt3_Init();
        DAC_Init();
        uart7_Init();
        err = uart2_init();
        if (FSP_SUCCESS != err)
        {
            while (1)
            {
                ;
            }
        }
        Gpt_Pwm_Setduty(88);
        uart2_send_string("RENESAS_UART2_READY\n");

        while (1)
        {
            /*
             * 从串口缓冲区里取一包完整数据
             * 一包数据以 '\n' 结束
             */

            if (uart2_get_line(rx_packet, sizeof(rx_packet), &rx_len))
            {
                uart2_handle_packet(rx_packet, rx_len);
            }

        }
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
